blank_issues_enabled: false
contact_links:
  - name: ğŸ¤” Feature Requests & Questions
    url: https://github.com/TanStack/react-table/discussions
    about: Please ask and answer questions here.
  - name: ğŸ’¬ Remix Discord Channel
    url: https://discord.gg/mQd7egN
    about: A dedicated discord server hosted by Tanner Linsley
  - name: ğŸ’¬ Tanstack Twitter
    url: https://twitter.com/tan_stack
    about: Stay up to date with new releases of our libraries
